# Generated by Django 3.2 on 2021-04-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=500)),
                ('sarting_bid', models.IntegerField()),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
