# Generated by Django 3.2 on 2021-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Collectibles', 'Collectibles'), ('Fashion', 'Fashion'), ('Sporting goods', 'Sporting goods'), ('Electronics', 'Electronics'), ('Home and Garden', 'Home and Garden'), ('Toys and Hobbies', 'Toys and Hobbies'), ('Entertainment', 'Entertainment'), ('Motors', 'Motors'), ('Other', 'Other')], max_length=64),
        ),
    ]
