# Generated by Django 3.2 on 2021-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listings_maximum_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
