# Generated by Django 3.2 on 2021-05-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='sarting_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
